exclude: ^clients/python/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        args:
          [
            --ignore-missing-imports,
            --no-strict-optional,
            --python-executable=.venv/bin/python,
          ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0 # Use the latest version or a specific version
    hooks:
      - id: commitizen
        stages: [commit-msg]
