[project]
name = "product-catalog-service"
version = "0.4.2"
description = "Product Catalog Service for managing product information."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Dmytro Tyzhnenko", email = "t.dmitry@gmail.com" }]
maintainers = [{ name = "Dmytro Tyzhnenko", email = "t.dmitry@gmail.com" }]
license = "MIT"
dependencies = [
    "beanie>=2.0.1",
    "fastapi>=0.127.0",
    "mypy>=2.1.0",
    "pendulum>=3.1.0",
    "pycountry>=24.6.1",
    "pydantic>=2.12.5",
    "pydantic-extra-types>=2.10.6",
    "pydantic-settings[yaml]>=2.12.0",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipython>=9.8.0",
    "mypy>=1.19.1",
    "prek>=0.3.2",
    "pytest>=9.0.3",
    "pytest-asyncio>=0.25.2",
    "ruff>=0.14.10",
    "pytest-cov>=7.0.0",
    "pytest-env>=1.2.0",
    "pytest-mongo>=3.2.1",
    "openapi-python-client>=0.28.0",
    "python-dateutil>=2.8.0",
    "types-python-dateutil>=2.8.0",
]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"
exclude = [
    ".git",
    ".venv",
    ".direnv",
    ".eggs",
    ".git-rewrite",
    ".mypy_cache",
    ".pytype",
    ".ruff_cache",
    ".tox",
    "__pycache__",
    "__pypackages__",
    "_build",
    "build",
    "buck-out",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.params.Depends",
    "fastapi.Query",
    "fastapi.params.Query",
    "fastapi.Path",
    "fastapi.Body",
    "fastapi.Header",
    "fastapi.Cookie",
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I", "C", "D", "Q", "S", "T"]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D213",
    "D203",
]

[tool.mypy]
python_version = "3.14"
