# Default application settings, to run the application for local development.
info:
  title: Product Catalog Service
  version: 0.1.0
  description: Service to manage product catalog and inventory

app:
  debug: true
  show_error_details: true
  cors_origins:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"

auth:
  rw_x_api_key: "your_rw_api_key_here"
  ro_x_api_key: "your_ro_api_key_here"

# database settings
db:
  driver: mongodb
  host: localhost
  user: <USER>
  password: <PASSWORD>
  port: 27017
  database: ledger
