info:
  title: Product Catalog Service
  version: 0.1.0
  description: Service to manage product catalog and inventory

app:
  debug: true
  cors_origins:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"

auth:
  rw_x_api_key: "set_your_rw_api_key_here"
  ro_x_api_key: "set_your_ro_api_key_here"

db:
  driver: mongodb
  host: localhost
  user: catalog_user
  password: set_your_secret_catalog_password
  port: 27017
  database: product_catalog
