info:
  title: Product Catalog Service
  version: 0.1.0
  description: Service to manage product catalog and inventory

app:
  debug: true
  cors_origins:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"

auth:
  rw_x_api_key:
  ro_x_api_key:

db:
  driver: mongodb
  host:
  user:
  password:
  port: 27017
  database:
